//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Installer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Installer.Localization.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for installing YuET!.
        /// </summary>
        public static string AllDoneTips {
            get {
                return ResourceManager.GetString("AllDoneTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following mods will be removed after continuing.
        /// </summary>
        public static string DeleteUnusedPluginsWarning {
            get {
                return ResourceManager.GetString("DeleteUnusedPluginsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to downloading BepInEx.
        /// </summary>
        public static string Download_BepInEx_Failed {
            get {
                return ResourceManager.GetString("Download.BepInEx.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to downloading YuET.
        /// </summary>
        public static string Download_TONX_Failed {
            get {
                return ResourceManager.GetString("Download.TONX.Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting download YuET.
        /// </summary>
        public static string Download_TONX_Requesting {
            get {
                return ResourceManager.GetString("Download.TONX.Requesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version is relatively backward.
        /// </summary>
        public static string DownloadChannel_Gitee_Desc {
            get {
                return ResourceManager.GetString("DownloadChannel.Gitee.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable, Recommended.
        /// </summary>
        public static string DownloadChannel_Github_Desc {
            get {
                return ResourceManager.GetString("DownloadChannel.Github.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable, Recommended.
        /// </summary>
        public static string DownloadChannel_kkGithub_Desc {
            get {
                return ResourceManager.GetString("DownloadChannel.kkGithub.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete redundant files.
        /// </summary>
        public static string FailedTo_Cleanup {
            get {
                return ResourceManager.GetString("FailedTo.Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extracting downloaded files.
        /// </summary>
        public static string FailedTo_Extracting {
            get {
                return ResourceManager.GetString("FailedTo.Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Folder.
        /// </summary>
        public static string GameFolder {
            get {
                return ResourceManager.GetString("GameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid Among Us folder used to install.
        /// </summary>
        public static string GameFolderEnterBoxPlaceholderText {
            get {
                return ResourceManager.GetString("GameFolderEnterBoxPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BepInEx Installed.
        /// </summary>
        public static string Install_BepInEx_Done {
            get {
                return ResourceManager.GetString("Install.BepInEx.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading BepInEx.
        /// </summary>
        public static string Install_BepInEx_Downloading {
            get {
                return ResourceManager.GetString("Install.BepInEx.Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting BepInEx to game directory.
        /// </summary>
        public static string Install_BepInEx_Extracting {
            get {
                return ResourceManager.GetString("Install.BepInEx.Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install BepInEx: Pending.
        /// </summary>
        public static string Install_BepInEx_Pending {
            get {
                return ResourceManager.GetString("Install.BepInEx.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YuET Installed.
        /// </summary>
        public static string Install_TONX_Done {
            get {
                return ResourceManager.GetString("Install.TONX.Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading YuET.
        /// </summary>
        public static string Install_TONX_Downloading {
            get {
                return ResourceManager.GetString("Install.TONX.Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install YuET: Pending.
        /// </summary>
        public static string Install_TONX_Pending {
            get {
                return ResourceManager.GetString("Install.TONX.Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Among Us game folder.
        /// </summary>
        public static string InvalidGameFolderTips {
            get {
                return ResourceManager.GetString("InvalidGameFolderTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Step.
        /// </summary>
        public static string LastStep {
            get {
                return ResourceManager.GetString("LastStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again using another download channel.
        /// </summary>
        public static string PlzTryAgainUsingOtherDownlodChennel {
            get {
                return ResourceManager.GetString("PlzTryAgainUsingOtherDownlodChennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again with Administrator access.
        /// </summary>
        public static string PlzTryAgainWithUAC {
            get {
                return ResourceManager.GetString("PlzTryAgainWithUAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download channel.
        /// </summary>
        public static string SelectDownloadChennel {
            get {
                return ResourceManager.GetString("SelectDownloadChennel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank KARPED1EM!.
        /// </summary>
        public static string ThanksKPD {
            get {
                return ResourceManager.GetString("ThanksKPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YuET Installer.
        /// </summary>
        public static string YuACInstaller {
            get {
                return ResourceManager.GetString("YuACInstaller", resourceCulture);
            }
        }
    }
}
